/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as FleetSlugRouteImport } from './routes/fleet.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetSlugRoute = FleetSlugRouteImport.update({
  id: '/fleet/$slug',
  path: '/fleet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/locations': typeof LocationsRoute
  '/services': typeof ServicesRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/locations': typeof LocationsRoute
  '/services': typeof ServicesRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/fleet': typeof FleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/locations': typeof LocationsRoute
  '/services': typeof ServicesRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/book' | '/locations' | '/services' | '/fleet/$slug' | '/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book' | '/locations' | '/services' | '/fleet/$slug' | '/fleet'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/locations'
    | '/services'
    | '/fleet/$slug'
    | '/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  LocationsRoute: typeof LocationsRoute
  ServicesRoute: typeof ServicesRoute
  FleetSlugRoute: typeof FleetSlugRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$slug': {
      id: '/fleet/$slug'
      path: '/fleet/$slug'
      fullPath: '/fleet/$slug'
      preLoaderRoute: typeof FleetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  LocationsRoute: LocationsRoute,
  ServicesRoute: ServicesRoute,
  FleetSlugRoute: FleetSlugRoute,
  FleetIndexRoute: FleetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
